modLoader="javafml"
loaderVersion="${loader_version_range}" # Use variable from gradle.properties
license="All Rights Reserved"

[[mods]]
modId="ae2craftinglens"
version="${mod_version}"
displayName="AE2 Crafting Lens"
authors="hcv2"
description='''
AE2 Crafting Lens - Pattern Provider Highlighting for Applied Energistics 2
'''

[[dependencies.ae2craftinglens]]
modId="forge"
mandatory=true
type="required"
versionRange="${forge_version_range}" # Use variable from gradle.properties
ordering="NONE"
side="BOTH"

[[dependencies.ae2craftinglens]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}" # Use variable from gradle.properties
ordering="NONE"
side="BOTH"

[[dependencies.ae2craftinglens]]
modId="ae2"
mandatory=true
type="required"
versionRange="[15.2.0,)"
ordering="AFTER"
side="BOTH"
